### ISSUE TITLE
I finally created my Background.icns!

### ISSUE THREAD

**Issue by kwmlman** [chris1111/Icnspack-Builder#2]
Since last September, I have been working hard to get the background of the opencore-bootloader.

Chris1111, I would like to express my sincere gratitude to you. (^+^)

![bigsur11 3beta-backgroundImage-oc0 6 6-210206](https://user-images.githubusercontent.com/76897014/107118528-f64c3400-68c4-11eb-831f-44ed0dd11d3a.jpg)

**Comment by kwmlman** [comment]
Another Image.

![bigsur11 3beta-backgroundImage-oc0 6 6-210206a](https://user-images.githubusercontent.com/76897014/107118709-e41ec580-68c5-11eb-86d2-3b84e853a61e.jpg)

**Comment by chris1111** [comment]
Here
https://github.com/chris1111/My-Simple-OC-Themes/issues/2
